--- 
- hosts: 172.31.5.163
  become: yes
  tasks:
  - name: i want to execute linux command
    command: hostname -f 
    register: myResult

  - name: i want to display myfirst task result 
    debug: 
       msg: "{{myResult}}"  