--- 
- hosts: mywebserver
  become: yes
  tasks:
  - name: install java on ubuntu ansible nodes 
    apt: 
      name: "{{myjavapckonubuntu}}"
      state: present 
    when: ansible_os_family =="Debian"

  - name: install java on redhat ansible nodes
    yum: 
      name: "{{myjavapackonredhat}}"
      state: present 
    when: ansible_os_family =="RedHat"      