--- 
- name: i want to create a tomcat group
  group:
    name: tomcat 
    state: present 

- name: i want to create tomcat user 
  user: 
    name: tomcat 
    shell: /bin/false   
    home: /opt/tomcat
    group: tomcat 
    state: present 

